### get all users
GET http://localhost:3001/api/users 

### post a new user
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "superuser",
    "password": "salainen"
}

### post a new user
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "admin2",
    "name": "admin2",
    "password": "salainen"
}

### delete a user
DELETE http://localhost:3001/api/users/669c4e75a7103a35c56a8963
